开始爬取：中国药科大学 【测试模式:ON】
========================================================
成功获取: 346, 网页失败: 0
开始爬取：test 【测试模式:OFF】
========================================================
成功获取: 62, 网页失败: 0
开始爬取：中国药科大学 【测试模式:OFF】
========================================================
成功获取: 481, 网页失败: 0
开始爬取：对外经济贸易大学 【测试模式:ON】
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 吴炳新 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=417&TypeName=%e5%ae%a2%e5%ba%a7%e6%95%99%e6%8e%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 黑瑞环 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=403&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 李惠华 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=487&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 许明月 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=402&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
网页爬取失败,未找到教师: http://bs.uibe.edu.cn/ibsnew_szdw/szdw_index.htm?num=0&page=../News/ListTeacher.aspx
网页爬取失败,未找到教师: http://insurance.uibe.edu.cn/szdw/szdw.html
========================================================
成功获取: 802, 网页失败: 2
开始爬取：对外经济贸易大学 【测试模式:ON】
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 吴炳新 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=417&TypeName=%e5%ae%a2%e5%ba%a7%e6%95%99%e6%8e%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 黑瑞环 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=403&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 李惠华 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=487&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 许明月 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=402&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
========================================================
成功获取: 963, 网页失败: 0
开始爬取：对外经济贸易大学 【测试模式:OFF】
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
method: Spider._write ERROR!
Traceback (most recent call last):
  File "C:\Users\ilove\Desktop\Utils\utils.py", line 121, in _write
    self.cursor.execute(
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python38\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'title' at row 1")
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 吴炳新 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=417&TypeName=%e5%ae%a2%e5%ba%a7%e6%95%99%e6%8e%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 黑瑞环 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=403&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 李惠华 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=487&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
item丢失字段: title  
	school : 对外经济贸易大学 -- None
	faculty : 国际经济贸易学院 -- None
	name : 许明月 -- 
	title : None -- ./../text()
	subject : *** -- ***
	cur : None -- 
	url : http://site.uibe.edu.cn/actionszdw/ViewTeacher.aspx?NewsID=402&TypeName=%e8%8d%a3%e4%bc%91%e6%95%99%e5%b8%88 -- None
========================================================
成功获取: 953, 网页失败: 10
开始爬取：首都师范大学 【测试模式:ON】
网页爬取失败,未找到教师: https://zf.cnu.edu.cn/szdw/zzxx/index.htm
========================================================
成功获取: 1482, 网页失败: 1
开始爬取：首都师范大学 【测试模式:OFF】
网页爬取失败,未找到教师: https://zf.cnu.edu.cn/szdw/zzxx/index.htm
========================================================
成功获取: 1482, 网页失败: 1
